version: '3.8'

services:
  map_dashboard:
    container_name: "map_dashboard"
    build:
      context: ../
      dockerfile: .docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - type: bind
        source: "../"
        target: "/app"
      - /app/node_modules
    command: pnpm run dev -- --host 0.0.0.0 --port 5173
    networks:
      - dashboard_dev

networks:
  dashboard_dev:
    external: true
